spring.application.name=chat
server.port=${PORT:8080}
server.address=0.0.0.0
spring.main.banner-mode=off

# Redis (Render)
spring.data.redis.url=redis://red-d75a3e2dbo4c739ag0hg:6379

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonushekhawat2077@gmail.com
spring.mail.password=lytg pfee urqz zqpi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://localhost:5432/Chatdb
spring.datasource.username=postgres
spring.datasource.password=heroic

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect